name: NaturalSchool
version: '1.3.5'
main: id.naturalsmp.naturalSchool.NaturalSchool
api-version: '1.21'
load: STARTUP
authors: [ NaturalTechnologies ]
website: https://naturalsmp.net
softdepend: [PlaceholderAPI, ItemsAdder, floodgate, Geyser-Spigot]

commands:
  naturalschool:
    description: NaturalSchool administrative control command.
    aliases: [nschool, ns]

permissions:
  naturalschool.admin:
    description: Allows administrative access to NaturalSchool commands.
    default: op
