name: NaturalSchool
version: '1.0.0'
main: id.naturalsmp.naturalSchool.NaturalSchool
api-version: '1.21'
load: STARTUP
authors: [ NaturalTechnologies ]
website: https://naturalsmp.net
softdepend: [PlaceholderAPI, ItemsAdder]

commands:
  naturalschool:
    description: NaturalSchool administrative control command.
    aliases: [nschool, ns]
    permission: naturalschool.admin

permissions:
  naturalschool.admin:
    description: Allows administrative access to NaturalSchool commands.
    default: op
